Webhook events: add ability to parse it and missing PaymentIntentCanceled event type
arlyon/async-stripe pull request #214
Opened 2022-04-20 10:14 UTC by lms11

This PR makes it possible to:
1. Parse a Webhook Event, by adding the missing fields
2. Add missing PaymentIntentCanceled event type

2022-04-20 10:15 UTC, lms11 commented
Types are listed here: https://stripe.com/docs/api/events/types

2022-04-21 19:03 UTC, arlyon commented
Thanks for this will review shortly :tada:

2022-04-24 17:28 UTC, arlyon requested changes
Looks good! Some small nitpicks but otherwise helpful. One thing I noticed is that apparently `tarpaulin` doesn't run against the examples (while `cargo test` does...) and this breaks one of them. I will get that sorted out in a later PR, but in the mean time could you please run `cargo test --features runtime-tokio-hyper` and fix the failing example? It's a trivial fix.

Thanks! :tada:

2022-04-24 17:28 UTC, arlyon commented on src/resources/webhook_events.rs
> +    pub account: Option<Box<String>>,
Is there a specific reason for boxing the string here?

2022-04-24 17:28 UTC, arlyon commented on src/resources/webhook_events.rs
> +    pub api_version: Option<Box<String>>,
See above

2022-04-24 17:28 UTC, arlyon commented on src/resources/webhook_events.rs
> +    pub request: Option<Box<NotificationEventRequest>>,
See above

2022-06-03 08:29 UTC, arlyon commented
Closed in favour of #233

2022-06-03 08:29 UTC, closed without merging