Add missing ids
arlyon/async-stripe pull request #236
Opened 2022-06-09 20:51 UTC by nazli-stripe

Adding a couple missing IDs to `ids.rs`

2022-06-15 12:17 UTC, arlyon commented
This is great, thank you @nazli-stripe! :) Going to wait for CI for the sake of process and merge this. :tada:

2022-06-15 13:12 UTC, arlyon requested changes

2022-06-15 21:08 UTC, nazli-stripe commented on src/ids.rs
> +def_id!(MandateId: "mandate_");
Accepted suggestion, thanks for catching!

2022-06-20 12:07 UTC, arlyon commented on src/ids.rs
> +def_id!(ConnectCollectionTransferId: "connct_");
```suggestion
def_id!(ConnectCollectionTransferId, "connct_");
```

2022-06-20 12:07 UTC, arlyon commented on src/ids.rs
> +def_id!(MandateId: "mandate_");
```suggestion
def_id!(MandateId, "mandate_");
```

2022-06-20 12:08 UTC, arlyon commented on src/ids.rs
> +def_id!(PaymentLinkId: "plink_");
```suggestion
def_id!(PaymentLinkId, "plink_");
```

2022-06-20 12:08 UTC, arlyon commented on src/ids.rs
> +def_id!(PriceId: "price_");
```suggestion
def_id!(PriceId, "price_");
```

2022-07-06 14:08 UTC, arlyon commented
Rebased this and merged it here: https://github.com/arlyon/async-stripe/pull/243 :) Thanks for the contribution

2022-07-06 14:08 UTC, closed without merging