Pin rust version to 1.65 instead of pinning time-core
arlyon/async-stripe pull request #426
Opened 2023-08-18 17:02 UTC by timsueberkrueb

# Summary

See https://github.com/arlyon/async-stripe/pull/421#issuecomment-1683880259

### Checklist

- [x] ran `cargo make fmt`
- [x] using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to hightlight user-facing fixes and features

2023-08-18 18:10 UTC, arlyon requested changes

2023-08-18 18:10 UTC, arlyon commented on Cargo.toml
> +rust-version = "1.65.0"
The version is actually set above so you can remove this line
```suggestion

```

2023-08-19 12:21 UTC, arlyon commented
looks like `time` now needs 1.67.0 so lets just bump our msrv to that while we are at it. change the version in cargo.toml and in the .github worflows (for CI)

2023-08-21 07:45 UTC, timsueberkrueb commented
@arlyon done, thank you!

2023-08-21 07:57 UTC, arlyon commented
Running CI again, TY

2023-08-23 06:21 UTC, timsueberkrueb commented
@arlyon the CI failing is an unrelated issue I assume?

2023-08-28 16:17 UTC, timsueberkrueb commented
Hey @arlyon, any update on this one? Thanks :)

2023-09-05 06:13 UTC, timsueberkrueb commented
Hey @arlyon, it would be really cool if we could land this and have a new crates.io release containing the fix. Thanks!

2023-09-05 12:12 UTC, arlyon commented
Fixed in this PR https://github.com/arlyon/async-stripe/pull/433

2023-09-05 12:12 UTC, closed without merging